// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BtGITk7iCV-COgGIqGWtlWW0k24U0CU',
    appId: '1:102230415574:web:069149b08bee2aea805177',
    messagingSenderId: '102230415574',
    projectId: 'tutionnotes-78ef3',
    authDomain: 'tutionnotes-78ef3.firebaseapp.com',
    storageBucket: 'tutionnotes-78ef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8y2mOl_5xmDiiaLZmQUuTtCZAjClz8g',
    appId: '1:102230415574:android:dce49f8d13c9dc72805177',
    messagingSenderId: '102230415574',
    projectId: 'tutionnotes-78ef3',
    storageBucket: 'tutionnotes-78ef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzMPnUSP3mE6aYEPKmdk35EXYX8o4Hoc',
    appId: '1:102230415574:ios:7f4c53de1e48a5cf805177',
    messagingSenderId: '102230415574',
    projectId: 'tutionnotes-78ef3',
    storageBucket: 'tutionnotes-78ef3.appspot.com',
    iosBundleId: 'com.example.tutionNotes',
  );
}
